language: node_js
node_js:
  - 12

install:
  - yarn install

script:
  - yarn test

before_deploy:
  - yarn build

deploy:
  provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true

after_deploy:
  - test ! -e /home/travis/.npm/_logs ; TRAVIS_TEST_RESULT=$?
